### ISSUE TITLE
grid-template-columns

### ISSUE THREAD

**Issue by khahn123** [bedimcode/responsive-portfolio-website-Alexa#32]
help me, why is my grid-template-columns value invalid?
![image](https://github.com/bedimcode/responsive-portfolio-website-Alexa/assets/133258761/3eb070f3-fa63-4c30-ac06-ab43f116b4d8)

**Comment by bedimcode** [comment]
Hello friend, the value is (1fr) not 1pr

**Comment by khahn123** [comment]
> Xin chào bạn, giá trị là (1fr) không phải 1pr

thank you, my silly little mistake =)))
